ezplatform.omnibox.search:
    path: /omnibox/search
    defaults:
        _controller: 'AdamWojs\EzPlatformOmniboxBundle\Controller\OmniboxController::searchAction'
    options:
        expose: true
