imports:
    - { resource: services/suggestion_providers.yaml }
    - { resource: services/commands.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezplatform.omnibox.components.autocomplete_js:
        parent: EzSystems\EzPlatformAdminUi\Component\ScriptComponent
        arguments:
            $src: 'https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js'
        tags:
            - { name: ezplatform.admin_ui.component, group: script-body }

    AdamWojs\EzPlatformOmniboxBundle\Controller\OmniboxController:
        tags:
            - { name: controller.service_arguments }
