imports:
    - { resource: services/suggestion_providers.yaml }
    - { resource: services/suggestion_context_resolvers.yaml }
    - { resource: services/commands.yaml }
    - { resource: services/parameter_resolvers.yaml }
    - { resource: services/user_settings.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezplatform.omnibox.components.autocomplete_js:
        parent: EzSystems\EzPlatformAdminUi\Component\ScriptComponent
        arguments:
            $src: 'https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js'
        tags:
            - { name: ezplatform.admin_ui.component, group: script-body }

    AdamWojs\EzPlatformOmniboxBundle\Controller\OmniboxController:
        tags:
            - { name: controller.service_arguments }

    AdamWojs\EzPlatformOmniboxBundle\Form\Type\SuggestionProviderChoiceType:
        arguments:
            $providers: !tagged_iterator { tag: ezplatform.omnibox.suggestion_provider, index_by: type }

    AdamWojs\EzPlatformOmniboxBundle\UI\ConfigProvider\SuggestionContextProvider:
        arguments:
            $resolvers: !tagged_iterator ezplatform.omnibox.suggestion_context_resolver
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'suggestionContext' }

