services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformOmniboxBundle\UI\ConfigProvider\SuggestionContextResolver\ContentViewSuggestionContextResolver:
        tags:
            - { name: ezplatform.omnibox.suggestion_context_resolver, priority: 0 }
