services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformOmniboxBundle\UI\UserSettings\SuggestionProviders:
        arguments:
            $providers: !tagged_iterator { tag: ezplatform.omnibox.suggestion_provider, index_by: type }
        tags:
            - { name: ibexa.user.setting.value, identifier: suggestion_providers }
            - { name: ibexa.user.setting.mapper.form, identifier: suggestion_providers }

    AdamWojs\EzPlatformOmniboxBundle\UI\UserSettings\VoiceAssistant:
        tags:
            - { name: ibexa.user.setting.value, identifier: voice_assistant }
            - { name: ibexa.user.setting.mapper.form, identifier: voice_assistant }
